---
baseurl: https://github.com/Metaswitch/calico-docker

calico_image: calico/node
calico_image_tag: v0.4.8

calico_binary: "{{ baseurl }}/releases/download/{{ calico_image_tag }}/calicoctl"

# Should be replaced with etcd.service.consul when we upgrade to Calico v0.5.0.
# Right now it can't resolve DNS from Consul. We can't start using 
# the latest Calico version as it utilizes some experimental Docker features.
etcd_service_name: 127.0.0.1
etcd_client_port: 2379

calico_etcdaddr: "{{ etcd_service_name }}:{{ etcd_client_port }}"

# Containers will be assigned IPs from this network range
calico_network: 192.168.0.0/16

# Containers are added to this profile for interconnectivity
calico_profile: dev
